# Generated by Django 5.0.14 on 2026-02-14 16:30

from django.db import migrations
from django.utils.text import slugify

def backfill_slug(apps, schema_editor):
    Tenant = apps.get_model('tenants', 'Tenant')
    for t in Tenant.objects.all().order_by('id'):
        if t.slug:
            continue

        base = slugify(t.name or '') or slugify(getattr(t, 'schema_name', '') or '') or f"tenant-{t.id}"
        slug = base
        i = 1
        while Tenant.objects.exclude(pk=t.pk).filter(slug=slug).exists():
            i += 1
            slug = f"{base}-{i}"

        t.slug = slug
        t.save(update_fields=['slug'])

class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_slug_tenant_status_tenant_updated_at'),
    ]

    operations = [
        migrations.RunPython(backfill_slug, migrations.RunPython.noop),
    ]
