# Generated by Django 5.0.14 on 2026-02-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_auditlog_entity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('test_connection', 'Test Connection'), ('trigger_sync', 'Trigger Sync'), ('sync_success', 'Sync Success'), ('sync_failed', 'Sync Failed'), ('archive_data', 'Archive Data')], max_length=30),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
