# Generated by Django 4.2.24 on 2026-02-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_auditlog_action_alter_auditlog_entity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='ai_api_key',
            field=models.CharField(blank=True, help_text='Encrypted API Key', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='ai_base_url',
            field=models.URLField(blank=True, help_text='Override base URL for AI provider', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='ai_model',
            field=models.CharField(default='gpt-4', help_text="e.g., 'gpt-4' or 'moonshotai/kimi-k2.5'", max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='ai_provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('kimi', 'Moonshot AI (Kimi)')], default='openai', max_length=50),
        ),
    ]
