# Generated by Django 5.0.14 on 2026-02-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='retention_ai_insights',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='tenant',
            name='retention_pull_requests',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='tenant',
            name='retention_work_items',
            field=models.IntegerField(default=12),
        ),
    ]
