import re
import logging

logger = logging.getLogger(__name__)

class PRDiffAnalyzer:
    """
    Analyzes unified diffs to compute the percentage of code generated by AI.
    It looks for AI GENERATED START/END markers, supporting various language comment syntax.
    """
    
    # Matches: # AI GENERATED START, // AI GENERATED CODE BLOCK, /* AI_GENERATED_START, <!-- AI-GENERATED CODE BLOCK
    START_RE = re.compile(
        r'^\s*(?:#|//|/\*|\*|<!--)\s*AI[\s\-_]*GENERATED[\s\-_]*(CODE[\s\-_]*)?(START|BLOCK)',
        re.IGNORECASE
    )
    
    # Matches: # AI GENERATED END, // AI GENERATED CODE BLOCK ENDS, */ AI_GENERATED_END, --> AI-GENERATED BLOCK ENDS
    END_RE = re.compile(
        r'^\s*(?:#|//|\*/|-->|\*)\s*AI[\s\-_]*GENERATED[\s\-_]*(CODE[\s\-_]*)?(END|BLOCK[\s\-_]*ENDS)',
        re.IGNORECASE
    )

    @classmethod
    def calculate_ai_usage(cls, diff_text: str) -> dict[str, float | int]:
        """
        Parses unified diff text.
        Counts total added lines ('+') and lines added inside AI blocks.
        """
        if not diff_text:
            return {'ai_lines': 0, 'total_lines': 0, 'percent': 0.0}

        total_lines = 0
        ai_lines = 0
        in_ai_block = False

        for line in diff_text.splitlines():
            # Reset block state if we see a new file header in a concatenated diff
            if line.startswith('--- ') or line.startswith('+++ ') or line.startswith('diff --git'):
                in_ai_block = False
                continue

            # Only care about additions. Ignore diff headers like +++ b/file.py
            if line.startswith('+') and not line.startswith('+++'):
                total_lines += 1
                
                # Strip the leading '+' and whitespace to match comment prefixes
                clean_line = line[1:].strip()
                
                if cls.START_RE.match(clean_line):
                    in_ai_block = True
                    # Don't increment ai_lines for the marker line itself
                    continue
                    
                if cls.END_RE.match(clean_line):
                    in_ai_block = False
                    continue
                
                # Count if we're inside an active block
                if in_ai_block:
                    ai_lines += 1

        percent = 0.0
        if total_lines > 0:
            percent = (ai_lines / total_lines) * 100.0

        return {
            'ai_lines': ai_lines,
            'total_lines': total_lines,
            'percent': round(percent, 2)
        }
