from __future__ import annotations
import re
import logging

logger = logging.getLogger(__name__)

class PRDiffAnalyzer:
    """
    Analyzes unified diffs to compute the percentage of code generated by AI.
    It looks for AI GENERATED START/END markers, supporting various language comment syntax.
    """
    
    # Matches: # AI GENERATED START, // AI GENERATED CODE BLOCK, /* AI_GENERATED_START, <!-- AI-GENERATED CODE BLOCK
    START_RE = re.compile(
        r'^\s*(?:#|//|/\*|\*|<!--)\s*AI[\s\-_]*GENERATED[\s\-_]*(CODE[\s\-_]*)?(START|BLOCK)',
        re.IGNORECASE
    )
    
    # Matches: # AI GENERATED END, // AI GENERATED CODE BLOCK ENDS, */ AI_GENERATED_END, --> AI-GENERATED BLOCK ENDS
    END_RE = re.compile(
        r'^\s*(?:#|//|\*/|-->|\*)\s*AI[\s\-_]*GENERATED[\s\-_]*(CODE[\s\-_]*)?(END|BLOCK[\s\-_]*ENDS)',
        re.IGNORECASE
    )

    # Matches trailing signatures: # AI generated via Antigravity IDE
    SIGNATURE_RE = re.compile(
        r'^\s*(?:#|//|/\*|\*|<!--)\s*AI\s*generated\s*via\s*Antigravity\s*IDE',
        re.IGNORECASE
    )

    @classmethod
    def calculate_ai_usage(cls, diff_text: str) -> dict[str, float | int]:
        """
        Parses unified diff text.
        Counts total added lines ('+') and lines added inside AI blocks.
        """
        if not diff_text:
            return {'ai_lines': 0, 'total_lines': 0, 'percent': 0.0}

        total_lines = 0
        ai_lines = 0
        in_ai_block = False
        
        # State block for trailing signatures
        hunk_added_lines = 0
        hunk_is_ai = False

        for line in diff_text.splitlines():
            # Reset block state if we see a new file header or context line change
            if line.startswith('--- ') or line.startswith('+++ ') or line.startswith('diff --git') or line.startswith('@@'):
                in_ai_block = False
                hunk_added_lines = 0
                hunk_is_ai = False
                continue
                
            # If we hit a context line (starts with space), it means the continuous stream of additions broke
            if line.startswith(' '):
                hunk_added_lines = 0
                hunk_is_ai = False
                continue

            # Only care about additions. Ignore diff headers like +++ b/file.py
            if line.startswith('+') and not line.startswith('+++'):
                total_lines += 1
                hunk_added_lines += 1
                
                # Strip the leading '+' and whitespace to match comment prefixes
                clean_line = line[1:].strip()
                
                if cls.START_RE.match(clean_line):
                    in_ai_block = True
                    # Don't increment ai_lines for the marker line itself
                    continue
                    
                if cls.END_RE.match(clean_line):
                    in_ai_block = False
                    continue
                    
                if cls.SIGNATURE_RE.match(clean_line):
                    # Found a trailing signature, mark the current hunk additions as AI
                    if not in_ai_block and not hunk_is_ai:
                        hunk_is_ai = True
                        # Retroactively add the lines we've seen in this continuous stream
                        # subtracting 1 so we don't count the signature line itself
                        ai_lines += max(0, hunk_added_lines - 1)
                    continue
                
                # Count if we're inside an active block or a marked hunk
                if in_ai_block or hunk_is_ai:
                    ai_lines += 1

        percent = 0.0
        if total_lines > 0:
            percent = (ai_lines / total_lines) * 100.0

        return {
            'ai_lines': ai_lines,
            'total_lines': total_lines,
            'percent': round(percent, 2)
        }
