# Generated by Django 4.2.30 on 2026-05-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='org_chart',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
