# Generated by Django 4.2.29 on 2026-05-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_org_chart_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeengagementcalendar',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='holidaycalendar',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
