# Generated by Django 4.2.29 on 2026-05-12 10:46

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_learninganddevelopment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('onboarding_file', models.FileField(upload_to=homepage.models.image_upload_path)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
