# Generated by Django 4.2.30 on 2026-05-20 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenant_ai_api_key_tenant_ai_base_url_tenant_ai_model_and_more'),
        ('homepage', '0006_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='tenant_id',
            field=models.ForeignKey(default=1, help_text='Tenant ID', on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
            preserve_default=False,
        ),
    ]
