# Generated by Django 4.2.30 on 2026-05-27 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_holiday_tenant_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Org_chart',
        ),
    ]
