# Generated by Django 4.2.30 on 2026-09-24 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenant_ai_api_key_tenant_ai_base_url_tenant_ai_model_and_more'),
        ('homepage', '0008_delete_org_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='tenant_id',
            field=models.ForeignKey(help_text='Tenant ID', on_delete=django.db.models.deletion.DO_NOTHING, to='tenants.tenant'),
        ),
    ]
