# Generated by Django 4.2.29 on 2026-04-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PUBLISHED', 'PUBLISHED'), ('IN_REVIEW', 'IN_REVIEW'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='DRAFT', max_length=20),
        ),
    ]
