# Generated by Django 4.2.29 on 2026-04-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_tag_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metadatacategory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
