# Generated by Django 4.2.29 on 2026-04-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_alter_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='DRAFT', max_length=20),
        ),
    ]
