# Generated by Django 4.2.29 on 2026-04-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0004_metadatacategory_is_deleted_tag_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('UNDER_REVIEW', 'UNDER_REVIEW'), ('DRAFT', 'DRAFT'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='DRAFT', max_length=20),
        ),
    ]
