# Generated by Django 4.2.29 on 2026-04-14 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0004_metadatacategory_is_deleted_tag_is_deleted'),
    ]

    operations = [
    ]

