# Generated by Django 4.2.30 on 2026-05-07 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0005_alter_document_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='document',
            name='status',
        ),
    ]
