# Generated by Django 4.2.28 on 2026-02-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_data_notification_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('compliance_failure', 'Compliance Failure'), ('etl_failure', 'ETL Failure'), ('sprint_ending', 'Sprint Ending Soon'), ('exception_approved', 'DMT Exception Approved'), ('ai_insight', 'AI Insight'), ('password_reset', 'Password Reset')], default='info', max_length=30),
        ),
    ]
