# Generated by Django 6.0.6 on 2026-07-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('compliance_failure', 'Compliance Failure'), ('etl_failure', 'ETL Failure'), ('sprint_ending', 'Sprint Ending Soon'), ('exception_approved', 'DMT Exception Approved'), ('ai_insight', 'AI Insight'), ('password_reset', 'Password Reset'), ('qucik_update', 'Qucik Update')], default='info', max_length=30),
        ),
    ]
