# Generated by Django 5.0.14 on 2026-02-13 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_integration_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_work_items', models.IntegerField(default=0)),
                ('compliant_work_items', models.IntegerField(default=0)),
                ('compliance_rate', models.FloatField(default=0.0)),
                ('avg_cycle_time_hours', models.FloatField(default=0.0)),
                ('prs_merged_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='HistoricalSprintMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocity', models.IntegerField(default=0)),
                ('final_compliance_rate', models.FloatField(default=0.0)),
                ('ai_efficiency_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sprint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='data.sprint')),
            ],
        ),
    ]
