# Generated by Django 5.0.14 on 2026-02-15 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='data.integration'),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='resolved_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pull_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pullrequeststatus',
            name='pull_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='data.pullrequest'),
        ),
        migrations.AddField(
            model_name='historicalsprintmetric',
            name='sprint',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='data.sprint'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='data.integration'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='resolved_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='work_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workitem',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items', to='data.sprint'),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='work_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pull_requests', to='data.workitem'),
        ),
    ]
