# Generated by Django 5.0.14 on 2026-02-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiinsight',
            name='integration',
        ),
        migrations.RemoveField(
            model_name='workitem',
            name='integration',
        ),
        migrations.RemoveField(
            model_name='pullrequest',
            name='integration',
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='source_config_id',
            field=models.IntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='source_config_id',
            field=models.IntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workitem',
            name='source_config_id',
            field=models.IntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Integration',
        ),
    ]
