# Generated by Django 4.2.24 on 2026-02-15 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_remove_aiinsight_integration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_source_id', models.CharField(max_length=100)),
                ('developer_email', models.EmailField(max_length=254)),
                ('developer_name', models.CharField(max_length=255)),
                ('sprint_name', models.CharField(max_length=100)),
                ('sprint_end_date', models.DateField()),
                ('story_points_completed', models.FloatField(default=0)),
                ('items_completed', models.IntegerField(default=0)),
                ('commits_count', models.IntegerField(default=0)),
                ('prs_authored', models.IntegerField(default=0)),
                ('prs_merged', models.IntegerField(default=0)),
                ('prs_reviewed', models.IntegerField(default=0)),
                ('avg_review_time_hours', models.FloatField(blank=True, null=True)),
                ('defects_attributed', models.IntegerField(default=0)),
                ('coverage_avg_percent', models.FloatField(blank=True, null=True)),
                ('dmt_compliance_rate', models.FloatField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'data_developermetrics',
            },
        ),
        migrations.CreateModel(
            name='SprintMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_name', models.CharField(max_length=100)),
                ('sprint_start_date', models.DateField()),
                ('sprint_end_date', models.DateField()),
                ('total_story_points_committed', models.FloatField(default=0)),
                ('total_story_points_completed', models.FloatField(default=0)),
                ('velocity', models.FloatField(default=0)),
                ('items_completed', models.IntegerField(default=0)),
                ('stories_completed', models.IntegerField(default=0)),
                ('bugs_completed', models.IntegerField(default=0)),
                ('defects_found_post_release', models.IntegerField(default=0)),
                ('defect_density_per_100_points', models.FloatField(default=0)),
                ('total_items', models.IntegerField(default=0)),
                ('compliant_items', models.IntegerField(default=0)),
                ('compliance_rate_percent', models.FloatField(default=0)),
                ('avg_cycle_time_days', models.FloatField(blank=True, null=True)),
                ('avg_lead_time_days', models.FloatField(blank=True, null=True)),
                ('total_blocked_days', models.IntegerField(default=0)),
                ('avg_blocked_days_per_item', models.FloatField(default=0)),
                ('total_prs_merged', models.IntegerField(default=0)),
                ('avg_time_to_first_review_hours', models.FloatField(blank=True, null=True)),
                ('prs_with_reviews_percent', models.FloatField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'data_sprintmetrics',
            },
        ),
        migrations.RemoveField(
            model_name='historicalsprintmetric',
            name='sprint',
        ),
        migrations.AddField(
            model_name='workitem',
            name='ac_quality',
            field=models.CharField(blank=True, choices=[('incomplete', 'Incomplete'), ('testable', 'Testable'), ('final', 'Final')], max_length=20),
        ),
        migrations.AddField(
            model_name='workitem',
            name='assignee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workitem',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workitem',
            name='blocked_days_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workitem',
            name='blocked_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workitem',
            name='ci_evidence_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workitem',
            name='compliance_failures',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workitem',
            name='coverage_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workitem',
            name='created_in_system_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workitem',
            name='dmt_compliant',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workitem',
            name='dmt_exception_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workitem',
            name='dmt_exception_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workitem',
            name='exception_approver',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='workitem',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workitem',
            name='item_type',
            field=models.CharField(choices=[('story', 'Story'), ('bug', 'Bug'), ('task', 'Task'), ('epic', 'Epic')], default='task', max_length=20),
        ),
        migrations.AddField(
            model_name='workitem',
            name='pr_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workitem',
            name='raw_source_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='workitem',
            name='reviewer_dmt_signoff',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workitem',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workitem',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workitem',
            name='status_category',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=20),
        ),
        migrations.AddField(
            model_name='workitem',
            name='unit_test_task_present',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workitem',
            name='unit_testing_status',
            field=models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('done', 'Done'), ('exception_approved', 'Exception Approved')], max_length=30),
        ),
        migrations.AddField(
            model_name='workitem',
            name='updated_in_system_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='status',
            field=models.CharField(db_index=True, default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='external_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='workitem',
            unique_together={('source_config_id', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['dmt_compliant', 'status_category'], name='data_workit_dmt_com_4667cc_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['source_config_id', 'external_id'], name='data_workit_source__33304b_idx'),
        ),
        migrations.AlterModelTable(
            name='workitem',
            table='data_workitem',
        ),
        migrations.DeleteModel(
            name='HistoricalSprintMetric',
        ),
        migrations.AddIndex(
            model_name='sprintmetrics',
            index=models.Index(fields=['sprint_end_date'], name='data_sprint_sprint__2cdbb5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sprintmetrics',
            unique_together={('sprint_name', 'sprint_end_date')},
        ),
        migrations.AddIndex(
            model_name='developermetrics',
            index=models.Index(fields=['developer_source_id', 'sprint_end_date'], name='data_develo_develop_a04051_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='developermetrics',
            unique_together={('developer_source_id', 'sprint_name', 'sprint_end_date')},
        ),
        migrations.RemoveField(
            model_name='workitem',
            name='compliance_reason',
        ),
        migrations.RemoveField(
            model_name='workitem',
            name='is_compliant',
        ),
        migrations.RemoveField(
            model_name='workitem',
            name='type',
        ),
    ]
