# Generated by Django 5.0.14 on 2026-02-14 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_integration_deleted_at_sprint_deleted_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
