# Generated by Django 4.2.24 on 2026-02-16 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_developermetrics_sprintmetrics_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
