# Generated by Django 4.2.28 on 2026-02-19 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='ai_usage_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='data.workitem'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='story_points',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
