# Generated by Django 5.0.14 on 2026-02-14 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_notification_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='resolved_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pull_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='resolved_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='work_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
