# Generated by Django 4.2.28 on 2026-02-22 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_alter_sourceconfiguration_api_token_encrypted'),
        ('data', '0007_workitem_ai_usage_percent_workitem_parent_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sprintmetrics',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sprintmetrics',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.project'),
        ),
        migrations.AlterUniqueTogether(
            name='sprintmetrics',
            unique_together={('sprint_name', 'sprint_end_date', 'project')},
        ),
    ]
