# Generated by Django 4.2.28 on 2026-02-23 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_alter_sourceconfiguration_api_token_encrypted'),
        ('data', '0008_alter_sprintmetrics_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinsight',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.project'),
        ),
        migrations.AlterField(
            model_name='aiinsight',
            name='source_config_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
