# Generated by Django 5.0.14 on 2026-02-14 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_pullrequest_resolved_author_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RetentionPolicy',
        ),
    ]
