# Generated by Django 4.2.24 on 2026-02-26 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_alter_sourceconfiguration_api_token_encrypted'),
        ('data', '0009_aiinsight_project_alter_aiinsight_source_config_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='developermetrics',
            name='data_develo_develop_a04051_idx',
        ),
        migrations.AlterUniqueTogether(
            name='developermetrics',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='developermetrics',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.project'),
        ),
        migrations.AlterUniqueTogether(
            name='developermetrics',
            unique_together={('developer_source_id', 'sprint_name', 'sprint_end_date', 'project')},
        ),
        migrations.AddIndex(
            model_name='developermetrics',
            index=models.Index(fields=['developer_source_id', 'sprint_end_date', 'project'], name='data_develo_develop_ed3ae1_idx'),
        ),
    ]
