# Generated by Django 4.2.24 on 2026-02-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_remove_developermetrics_data_develo_develop_a04051_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developermetrics',
            name='ai_usage_percent',
            field=models.FloatField(default=0),
        ),
    ]
