# Generated by Django 4.2.24 on 2026-03-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_developermetrics_ai_usage_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinsight',
            name='insight_type',
            field=models.CharField(choices=[('general', 'General'), ('deep_sprint', 'Deep Sprint Analysis')], db_index=True, default='general', max_length=20),
        ),
    ]
