# Generated by Django 4.2.29 on 2026-03-08 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0012_add_aiinsight_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='ai_code_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='ai_generated_lines',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='diff_analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='pr_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='total_changed_lines',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workitem',
            name='code_ai_usage_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PullRequestReviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_email', models.EmailField(max_length=254)),
                ('reviewer_name', models.CharField(blank=True, max_length=255)),
                ('vote', models.IntegerField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewers', to='data.pullrequest')),
                ('resolved_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pull_request_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100)),
                ('source_config_id', models.IntegerField(db_index=True)),
                ('repository_name', models.CharField(max_length=255)),
                ('author_email', models.EmailField(max_length=254)),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('additions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('committed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='commits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_commit',
                'indexes': [models.Index(fields=['source_config_id', 'author_email'], name='data_commit_source__e968b2_idx'), models.Index(fields=['committed_at'], name='data_commit_committ_9250e6_idx')],
                'unique_together': {('source_config_id', 'external_id')},
            },
        ),
    ]
