# Generated by Django 4.2.29 on 2026-03-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_pullrequest_ai_code_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developermetrics',
            name='code_ai_usage_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sprintmetrics',
            name='ai_usage_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sprintmetrics',
            name='code_ai_usage_percent',
            field=models.FloatField(default=0),
        ),
    ]
