# Generated by Django 4.2.29 on 2026-03-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_developermetrics_code_ai_usage_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIdentityMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('canonical_name', models.CharField(max_length=255)),
                ('source_identities', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'data_useridentitymapping',
            },
        ),
    ]
