# Generated by Django 4.2.29 on 2026-03-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_useridentitymapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='author_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workitem',
            name='inferred_assignee',
            field=models.BooleanField(default=False),
        ),
    ]
