# Generated by Django 4.2.29 on 2026-03-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_pullrequest_author_name_workitem_inferred_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='external_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='pullrequest',
            unique_together={('source_config_id', 'repository_name', 'external_id')},
        ),
    ]
