# Generated by Django 4.2.30 on 2026-05-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_workitem_etl_attribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='pm_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='workitem',
            name='pm_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workitem',
            name='tech_lead_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='workitem',
            name='tech_lead_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
