# Generated by Django 4.2.30 on 2026-08-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_workitem_pm_tech_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='source_config_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='external_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='sprint',
            unique_together={('source_config_id', 'external_id')},
        ),
        migrations.AlterModelTable(
            name='sprint',
            table='data_sprint',
        ),
    ]
