# Generated by Django 5.0.14 on 2026-02-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('default_coverage_threshold', models.FloatField(default=80.0)),
            ],
            options={
                'db_table': 'public.projects',
            },
        ),
        migrations.CreateModel(
            name='SourceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('jira', 'Jira'), ('clickup', 'ClickUp'), ('azure_boards', 'Azure Boards'), ('github', 'GitHub'), ('azure_devops_git', 'Azure DevOps Git'), ('azure_devops', 'Azure DevOps')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('base_url', models.URLField()),
                ('api_token_encrypted', models.BinaryField(blank=True, null=True)),
                ('api_key', models.CharField(blank=True, help_text='Encrypted or stored safely in production', max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('workspace_id', models.CharField(blank=True, max_length=100, null=True)),
                ('config_json', models.JSONField(default=dict, help_text='Source specific config like board_id etc')),
                ('field_mappings', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('in_progress', 'In Progress'), ('never', 'Never')], default='never', max_length=20)),
                ('last_error_message', models.TextField(blank=True)),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('failure_alert_threshold', models.IntegerField(default=3)),
                ('historical_import_days', models.IntegerField(default=30)),
                ('historical_import_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'public.source_configurations',
            },
        ),
    ]
