# Generated by Django 5.0.14 on 2026-02-15 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='projects',
        ),
        migrations.AlterModelTable(
            name='sourceconfiguration',
            table='source_configurations',
        ),
    ]
