# Generated by Django 5.0.14 on 2026-02-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_alter_project_table_alter_sourceconfiguration_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceconfiguration',
            name='api_token_encrypted',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
