# Generated by Django 4.2.30 on 2026-05-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_alter_sourceconfiguration_api_token_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceconfiguration',
            name='current_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
