# Generated by Django 4.2.29 on 2026-03-11 10:25

from django.db import migrations, models
import newsapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to=newsapp.models.get_post_media_upload_path),
        ),
    ]
