# Generated by Django 4.2.29 on 2026-03-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_alter_post_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction_type',
            field=models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('haha', 'Haha'), ('sad', 'Sad')], max_length=50),
        ),
    ]
