# Generated by Django 4.2.29 on 2026-03-19 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_tempimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TempImage',
            new_name='Image',
        ),
    ]
