# Generated by Django 4.2.29 on 2026-03-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_rename_tempimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to='PostImages/'),
        ),
    ]
