# Generated by Django 4.2.29 on 2026-03-25 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import newsapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsapp', '0007_alter_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to=newsapp.models.temp_image_upload_path),
        ),
    ]
