# Generated by Django 4.2.29 on 2026-03-25 09:30

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_competitive_title_user_competitive_title_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.get_user_media_upload_path),
        ),
    ]
