# Generated by Django 4.2.30 on 2026-05-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_roletable_user_parent_alter_user_is_active_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='roletable',
            name='dep_name',
            field=models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('mobile', 'Mobile'), ('devops', 'DevOps'), ('qa', 'QA / Testing'), ('data', 'Data & Analytics'), ('design', 'Design / UX'), ('product', 'Product'), ('hr', 'HR'), ('finance', 'Finance'), ('sales', 'Sales'), ('marketing', 'Marketing'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='roletable',
            name='role_name',
            field=models.CharField(max_length=50),
        ),
    ]
