# Generated by Django 4.2.30 on 2026-05-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_roletable_dep_name_alter_roletable_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roletable',
            name='dep_name',
            field=models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('mobile', 'Mobile'), ('devops', 'DevOps'), ('qa', 'QA / Testing'), ('data', 'Data & Analytics'), ('design', 'Design / UX'), ('product', 'Product'), ('hr', 'HR'), ('finance', 'Finance'), ('sales', 'Sales'), ('marketing', 'Marketing'), ('other', 'Other'), ('aiml', 'AI & ML')], default='other', max_length=20),
        ),
    ]
