# Generated by Django 4.2.30 on 2026-05-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_roletable_dep_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='org_visibility',
            field=models.BooleanField(default=False),
        ),
    ]
