# Generated by Django 4.2.30 on 2026-05-27 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_org_visibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='org_visibility',
            new_name='org_chart_visibility',
        ),
    ]
