# Generated by Django 4.2.29 on 2026-06-10 06:16

from django.db import migrations, models


def populate_departments(apps, schema_editor):
    Department = apps.get_model('users', 'Department')
    RoleTable = apps.get_model('users', 'RoleTable')
    
    # Pre-defined choices from RoleTable.DepartmentChoices
    initial_departments = [
        'backend', 'frontend', 'mobile', 'devops', 'qa', 'data',
        'design', 'product', 'hr', 'finance', 'sales', 'marketing', 'other', 'aiml'
    ]
    
    # Get distinct department names from existing RoleTable entries
    existing_departments = RoleTable.objects.values_list('dep_name', flat=True).distinct()
    
    # Combine pre-defined and existing departments, filtering out None/empty values
    all_departments = set(initial_departments)
    for dep in existing_departments:
        if dep:
            all_departments.add(dep)
    
    for dep_name in all_departments:
        Department.objects.get_or_create(name=dep_name)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_org_visibility_user_org_chart_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='roletable',
            name='dep_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunPython(populate_departments, migrations.RunPython.noop),
    ]
