# Generated by Django 6.0.6 on 2026-07-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_department_alter_roletable_dep_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'custom_permissions',
            },
        ),
        migrations.AddField(
            model_name='roletable',
            name='permissions',
            field=models.ManyToManyField(blank=True, db_table='role_permissions_mapping', related_name='roles', to='users.custompermission'),
        ),
    ]
