# Generated by Django 6.0.6 on 2026-07-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_custompermission_roletable_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='roletable',
            name='role_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
