# Generated by Django 4.2.30 on 2026-08-24 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_companybaseline'),
        ('users', '0013_roletable_role_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='roletable',
            name='role_category',
            field=models.CharField(blank=True, help_text='Role Category e.g. DEVELOPER, QA, DESIGNER, DEVOPS, etc.', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ResourceAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('percentage_allocated', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_allocations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_allocations', to='configuration.project')),
            ],
            options={
                'db_table': 'resource_allocations',
                'indexes': [models.Index(fields=['developer', 'year', 'month', 'status'], name='resource_al_develop_e03523_idx'), models.Index(fields=['year', 'month', 'status'], name='resource_al_year_cbbd16_idx')],
                'unique_together': {('developer', 'project', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyAllocationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_allocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'monthly_allocation_statuses',
                'indexes': [models.Index(fields=['year', 'month', 'status'], name='monthly_all_year_709c69_idx')],
                'unique_together': {('month', 'year')},
            },
        ),
    ]
